/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp;

public class App {
  public static void main(String[] args) {

    // System - 상자(클래스 class) ,
    // out - 도구(객체 object, instance),
    // println - 기능(funtion, 메서드 method)
    // () - 기능수행에 필요한 값 = 아규먼트(argument) = 파라미터 (parameter)
    // \n - 이스케이프 캐릭터

    System.out.println("나의 목록 관리 시스템");
    System.out.println("-------------------------");

    int no = 100;
    String name = "홍길동";
    int age = 20;
    boolean working = true;
    char gender = 'M';
    float leftEye = 1.5f;
    float rightEye = 1.0f;

    System.out.printf("번호 : %d\n", no);
    System.out.printf("이름: %s\n" , name);
    System.out.printf("나이: %d\n", age);
    System.out.printf("재직자: %b\n", working);    
    System.out.printf("성별(남자(M), 여자(W)): %c\n", gender);
    System.out.printf("좌우 력: %.1f, %.1f\n", leftEye, rightEye);
    
  }
}
