/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp;

public class App {
  public static void main(String[] args) {

    // System - 상자(클래스 class) ,
    // out - 도구(객체 object, instance),
    // println - 기능(funtion, 메서드 method)
    // () - 기능수행에 필요한 값 = 아규먼트(argument) = 파라미터 (parameter)
    // \n - 이스케이프 캐릭터

    System.out.println("나의 목록 관리 시스템");
    System.out.println("-------------------------");

    System.out.print("번호 : ");
    System.out.println(100);

    System.out.printf("나이: %s" , "홍길동");
    System.out.println();

    System.out.println("나이: " + 20);

    System.out.printf("재직자: %b\n", true);
    
    System.out.printf("성별(남자(M), 여자(W)): %c\n", 'M');
    System.out.printf("좌우 력: %f. %f\n", 1.5f, 1.0f);
    
  }
}
